apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-metric-server-pods-watch-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metric-server-pods-watch-cluster-role
subjects:
- kind: ServiceAccount
  name: custom-metric-server-service-account
  namespace: custom-metrics-ns