apiVersion: v1
kind: Service
metadata:
  namespace: custom-metrics-ns
  name: custom-metric-server-service
spec:
  selector:
    app: custom-metric-server
  ports:
  - name: https
    port: 443
    targetPort: 8443
  - name: http
    port: 80
    targetPort: 8080